### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by jhochman** [ustims/PhantomJS-Dart#1]
Line #34 is looking for simply linefeed ('\n'), but on Windows it's really carriage-return & linefeed ('\r\n')

**Comment by jhochman** [comment]
Linfe #21 should use PathLib.separator instead of '/'

**Comment by ustims** [comment]
Thanks, will fix that tomorrow.

**Comment by ustims** [comment]
Fixed, try it please and give me a feedback.

**Comment by jhochman** [comment]
Confirmed - works for me. Thanks!
